title: Juan Mendez
logo: /assets/img/Scrinshot circle.jpg
[[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/juanportet/" 
show_downloads: true
theme: jekyll-theme-minimal
