title: Juan Mendez
logo: /assets/img/Scrinshot circle.jpg
description: Experienced engineer proficient in predictive and classification modeling, data visualization, and analysis. Eager to contribute to team success through hard work, attention to detail, and a resilient mindset. Motivated to learn, grow and excel in anything I set my eye on. 
  <br><br>
  <a href="https://www.linkedin.com/in/juanportet/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
show_downloads: false
theme: jekyll-theme-minimal


