title: Juan Mendez
logo: /assets/img/Scrinshot circle.jpg
description: HELLOOO
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-lundeen-b49b8390/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <br><br>
show_downloads: true
theme: jekyll-theme-minimal


