title: Juan Mendez
logo: /assets/img/Scrinshot circle.jpg
description: HELLOOO
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/juanportet/"> <img "/assets/img/linkedin.jpeg"> </a> 
  <br><br>
  <br><br>
show_downloads: true
theme: jekyll-theme-minimal


